spring.application.name=main-service

debug=false

## master data source
spring.master.datasource.driver-class-name=org.postgresql.Driver
spring.master.datasource.jdbc-url=jdbc:postgresql://${postgres.server:postgres-db}:${postgres.port:5432}/${postgres.db:bd_social}
spring.master.datasource.schema=${postgres.db.schema:bd_social}

spring.liquibase.default-schema=${postgres.db.schema:bd_social}

spring.data.redis.host=redis-cache
spring.data.redis.port=6379

spring.rabbitmq.host=rabbit-mq
spring.rabbitmq.port=5672
spring.rabbitmq.username=guest
spring.rabbitmq.password=guest

#chat-service.client.url=http://${chat-service.client.server:chat-service}:${chat-service.client.port:8080}/
chat-service.client.url=http://${chat-service.client.server:nginx-chat-service}:${chat-service.client.port:80}/

logging.level.root=INFO
logging.level.org.springframework.web=DEBUG
logging.file.name=logs/main-service.log
logging.pattern.console=%d{yyyy-MM-dd HH:mm:ss.SSS} [%X{requestId}] [%thread] %-5level %logger{36} - %msg%n
logging.pattern.file=%d{yyyy-MM-dd HH:mm:ss.SSS} [%X{requestId}] [%thread] %-5level %logger{36} - %msg%n