events {
  worker_connections  1024;
}

http {
    upstream myapp {
        server chat-service1:8080 max_fails=2 fail_timeout=30s;
        server chat-service2:8080 max_fails=2 fail_timeout=30s;
    }

    server {
        listen 80;

        access_log /etc/nginx/logs/access.log;
        error_log /etc/nginx/logs/error.log;

        location / {
            proxy_pass http://myapp;
            proxy_connect_timeout 5s;
            proxy_send_timeout 30s;
            proxy_read_timeout 30s;
        }
    }
}