name: otus_hw

services:
  main-app:
    container_name: main-service
    build:
      # from project root
      context: ../
      dockerfile: ./main-service/docker/Dockerfile
    image: main-service-app:${APP_VERSION}
    environment: &MAIN-AUTH
      POSTGRES_SERVER: postgres-db
      POSTGRES_DB: bd_social
      POSTGRES_DB_SCHEMA: bd_social
      POSTGRES_USER: bd_admin
      POSTGRES_PASSWORD: bd_pass
    restart: unless-stopped
    ports:
      - "8080:8080"
      - "5005:5005"
    networks:
      - social-network
    depends_on:
      postgres-db:
        condition: service_healthy
      redis-cache:
        condition: service_started
      rabbit-mq:
        condition: service_started

  chat-service1:
    container_name: chat-service1
    build:
      # from project root
      context: ../
      dockerfile: ./chat-service/docker/Dockerfile
    image: chat-service-app:${APP_VERSION}
    environment: &CHAT-AUTH
      POSTGRES_SERVER: chat-postgres-db
      POSTGRES_REPLICA_SERVER: haproxy-chat-service
      POSTGRES_DB: bd_dialogs
      POSTGRES_DB_SCHEMA: bd_dialogs
      POSTGRES_USER: bd_admin
      POSTGRES_PASSWORD: bd_pass
      POSTGRES_PORT: 5432
    restart: unless-stopped
    ports:
      - "8082:8080"
      - "5006:5005"
    networks:
      - social-network
    depends_on:
      haproxy-chat-service:
        condition: service_started

  chat-service2:
    container_name: chat-service2
    build:
      # from project root
      context: ../
      dockerfile: ./chat-service/docker/Dockerfile
    image: chat-service-app:${APP_VERSION}
    environment: *CHAT-AUTH
    restart: unless-stopped
    ports:
      - "8083:8080"
    networks:
      - social-network
    depends_on:
      chat-service1:
        condition: service_started

  postgres-db:
    container_name: postgres-db
    image: postgres:15-alpine
    environment: *MAIN-AUTH
    restart: unless-stopped
    ports:
      - "5432:5432"
    networks:
      - social-network
    volumes:
      - ../main-service/docker/init.sql:/docker-entrypoint-initdb.d/init.sql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -d $$POSTGRES_DB -U $$POSTGRES_USER"]
      interval: 10s
      timeout: 5s
      retries: 3

#  chat-postgres-db:
#    container_name: chat-postgres-db
#    image: postgres:15-alpine
#    environment: *CHAT-AUTH
#    restart: unless-stopped
#    ports:
#      - "5433:5432"
#    networks:
#      - social-network
#    volumes:
#      - ../chat-service/docker/init.sql:/docker-entrypoint-initdb.d/init.sql
#    healthcheck:
#      test: ["CMD-SHELL", "pg_isready -d $$POSTGRES_DB -U $$POSTGRES_USER"]
#      interval: 10s
#      timeout: 5s
#      retries: 3

  redis-cache:
    container_name: redis-cache
    image: redis:8-alpine
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data
    networks:
      - social-network
    restart: unless-stopped

  rabbit-mq:
    container_name: rabbit-mq
    image: rabbitmq:4-management-alpine
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
    ports:
      - "5672:5672"
      - "15672:15672"
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq/mnesia/
    networks:
      - social-network
    restart: unless-stopped

  nginx-chat-service:
    container_name: nginx
    image: nginx:1.28-alpine
    volumes:
      - ../other/nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ../other/nginx/logs:/etc/nginx/logs
    ports:
      - "8081:80"
    restart: unless-stopped
    networks:
      - social-network
    depends_on:
      chat-service1:
        condition: service_started

  haproxy-chat-service:
    image: haproxy:3.3-alpine
    container_name: haproxy-chat-service
    environment:
      PG_SLAVE1: chat-postgres-db-slave1:5432
      PG_SLAVE2: chat-postgres-db-slave2:5432
    volumes:
      - "../other/haproxy/haproxy.cfg:/usr/local/etc/haproxy/haproxy.cfg"
    ports:
      - "5434:5432"
      - "8404:8404"
    restart: unless-stopped
    networks:
      - social-network

networks:
  social-network:
    driver: bridge
    external: true

volumes:
  redis-data:
  rabbitmq_data:
