spring.application.name=chat-service

debug=false

# master data source
spring.master.datasource.driver-class-name=org.postgresql.Driver
spring.master.datasource.jdbc-url=jdbc:postgresql://${postgres.server}:${postgres.port:5432}/${postgres.db:bd_dialogs}
spring.master.datasource.schema=${postgres.db.schema:bd_social}

# replica data source
spring.replica.datasource.enable=true
spring.replica.datasource.driver-class-name=org.postgresql.Driver
spring.replica.datasource.jdbc-url=jdbc:postgresql://${postgres.replica.server}:${postgres.replica.port:5432}/${postgres.replica.db:bd_dialogs}
spring.replica.datasource.schema=${postgres.db.schema:bd_dialogs}

spring.liquibase.default-schema=${postgres.db.schema:bd_dialogs}

logging.level.root=INFO
logging.level.org.springframework.web=DEBUG
logging.file.name=logs/chat-service.log
logging.pattern.console=%d{yyyy-MM-dd HH:mm:ss.SSS} [%X{requestId}] [%thread] %-5level %logger{36} - %msg%n
logging.pattern.file=%d{yyyy-MM-dd HH:mm:ss.SSS} [%X{requestId}] [%thread] %-5level %logger{36} - %msg%n